# Generated by Django 2.1.5 on 2019-11-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table='label',
        ),
    ]
