# Generated by Django 2.1.5 on 2019-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0002_auto_20191116_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='is_good',
            field=models.IntegerField(choices=[(0, 'BAD'), (1, 'GOOD')], default=0),
        ),
    ]
